# Generated by Django 5.0.2 on 2024-03-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_path', models.FilePathField(max_length=200)),
                ('media_type', models.CharField(max_length=200)),
                ('media_created_at', models.DateTimeField(verbose_name="date meme'd")),
                ('voice_recording_path', models.FilePathField(max_length=200)),
                ('voice_recording_created_at', models.DateTimeField(verbose_name='date recorded')),
                ('voice_recording_transcript', models.TextField()),
                ('authors', models.CharField(max_length=200)),
                ('season', models.PositiveSmallIntegerField()),
                ('subseason', models.CharField(max_length=200)),
            ],
        ),
    ]
