version: '3.8'

services:
  web:
    image: ghcr.io/danielkinahan/gargboyz:latest
    command: gunicorn gargboyz.wsgi:application --workers=4 --bind 0.0.0.0:8000 --preload --access-logfile '-' --error-logfile '-'
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - gargboyz
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - gargboyz
  nginx:
    image: ghcr.io/danielkinahan/gargboyz-nginx:latest
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 9189:443
      - 9188:80
    depends_on:
      - web
    networks:
      - gargboyz
      - caddy

volumes:
  postgres_data:
  static_volume:
  media_volume:


networks:
  gargboyz:
    name: gargboyz
  caddy:
    name: caddy
    external: true
