services:
  web:
    image: ghcr.io/danielkinahan/gargboyz:latest
    container_name: gargboyz
    command: gunicorn gargboyz.wsgi:application --workers=4 --bind 0.0.0.0:8000 --preload --access-logfile '-' --error-logfile '-'
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./mediafiles:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - gargboyz
  db:
    image: postgres:15
    container_name: gargboyz-db
    volumes:
      - ./gargboyz-db:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - gargboyz
  nginx:
    image: ghcr.io/danielkinahan/gargboyz-nginx:latest
    container_name: gargboyz-nginx
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./mediafiles:/home/app/web/mediafiles
    depends_on:
      - web
    networks:
      - gargboyz
      - caddy

networks:
  gargboyz:
    name: gargboyz
  caddy:
    name: caddy
    external: true
