version: "3.8"

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  django:
    image: ghcr.io/danielkinahan/gargboyz:latest
    volumes:
      - ./.env:/app/.env
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "9999:80"
