version: '3.8'

services:
  web:
    image: ghcr.io/danielkinahan/gargboyz:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile.prod
    command: gunicorn gargboyz.wsgi:application -w 4 --bind 0.0.0.0:8000 --preload
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    image: ghcr.io/danielkinahan/nginx:latest
    # build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 9189:443
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
