# Generated by Django 5.0.2 on 2024-03-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='media_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='voice_recording_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
