# Generated by Django 5.0.2 on 2024-03-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('declared_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('media_path', models.FilePathField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, max_length=50)),
                ('media_created_at', models.DateField(blank=True, null=True)),
                ('voice_recording_path', models.FilePathField(blank=True, null=True)),
                ('voice_recording_created_at', models.DateTimeField(blank=True, null=True)),
                ('voice_recording_transcript', models.TextField(blank=True, null=True)),
                ('season', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('subseason', models.CharField(blank=True, max_length=100)),
                ('authors', models.ManyToManyField(blank=True, to='memes.author')),
            ],
        ),
    ]
