# Generated by Django 5.0.2 on 2024-03-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_rename_media_created_at_meme_meme_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='meme_created_at',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='meme_path',
            field=models.FileField(blank=True, upload_to='memes/'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='voice_recording_created_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='voice_recording_path',
            field=models.FileField(blank=True, upload_to='recordings/'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='voice_recording_transcript',
            field=models.TextField(blank=True),
        ),
    ]
