# Generated by Django 5.0.3 on 2024-04-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
