# Generated by Django 5.0.3 on 2024-04-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0008_meme_comment_count_meme_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='meme_created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='voice_recording_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
