# Generated by Django 5.0.2 on 2024-03-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_alter_meme_media_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='media_created_at',
            new_name='meme_created_at',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='media_type',
            new_name='meme_type',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='media_path',
        ),
        migrations.AddField(
            model_name='meme',
            name='meme_path',
            field=models.FileField(blank=True, null=True, upload_to='memes/'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='voice_recording_path',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
    ]
